import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, readFile } from 'fs/promises';
import { PrismaClient } from '@prisma/client';

const execAsync = promisify(exec);
const prisma = new PrismaClient();

// Track last restart time to prevent concurrent restarts
let lastRestartTime = 0;
const RESTART_COOLDOWN = 3000; // 3 seconds cooldown

// Path to the auto-generated NAS clients file
const NAS_CLIENTS_FILE = '/etc/freeradius/3.0/clients.d/nas-from-db.conf';

/**
 * Sync NAS entries from database to FreeRADIUS clients.d/nas-from-db.conf.
 * Idempotent: only writes the file when content actually changed.
 * 
 * Generates:
 * 1. Per-NAS client entries (individual IP + secret)
 * 2. Per-VPN-server gateway client entries (gateway IP with shared secret)
 *    Required because VPN CHR servers masquerade RADIUS traffic — all packets
 *    from NAS behind the same CHR arrive with the CHR gateway IP as source.
 *    All NAS behind the same VPN server MUST share the same RADIUS secret.
 * 
 * @returns true if the file was updated (reload needed), false if already in sync
 */
export async function syncNasClients(): Promise<boolean> {
  try {
    // Fetch all active NAS entries with their VPN client → VPN server chain
    const nasEntries = await prisma.router.findMany({
      where: { isActive: true },
      select: {
        nasname: true,
        shortname: true,
        secret: true,
        type: true,
        vpnClientId: true,
        vpnClient: {
          select: {
            vpnIp: true,
            isRadiusServer: true,
            vpnServer: {
              select: {
                id: true,
                name: true,
                subnet: true,
              },
            },
          },
        },
      },
    });

    if (nasEntries.length === 0) return false;

    // Build the expected config (without timestamp so diff is stable)
    const lines: string[] = [
      '# Auto-generated by salfanet-radius - DO NOT EDIT MANUALLY',
      '',
    ];

    // Track VPN server gateways to generate gateway client entries
    const vpnGateways = new Map<string, { gatewayIp: string; secret: string; serverName: string }>();

    for (const nas of nasEntries) {
      const safeShort = (nas.shortname || nas.nasname).replace(/[^a-z0-9_-]/gi, '_');
      lines.push(`client nas_${safeShort} {`);
      lines.push(`    ipaddr = ${nas.nasname}`);
      lines.push(`    secret = ${nas.secret}`);
      lines.push(`    shortname = ${safeShort}`);
      lines.push(`    nas_type = other`);
      lines.push(`    require_message_authenticator = no`);
      lines.push(`    limit_proxy_state = no`);
      lines.push(`}`);
      lines.push('');

      // Collect VPN server gateway info (skip the VPS itself = isRadiusServer)
      if (nas.vpnClient && nas.vpnClient.vpnServer && !nas.vpnClient.isRadiusServer) {
        const server = nas.vpnClient.vpnServer;
        if (!vpnGateways.has(server.id)) {
          // Derive gateway IP: subnet "10.20.30.0/24" → gateway "10.20.30.1"
          const subnetBase = server.subnet.split('/')[0]; // "10.20.30.0"
          const parts = subnetBase.split('.');
          parts[3] = '1';
          const gatewayIp = parts.join('.');
          const safeName = server.name.replace(/[^a-z0-9_-]/gi, '_').toLowerCase();

          vpnGateways.set(server.id, {
            gatewayIp,
            secret: nas.secret, // First NAS's secret becomes the VPN server gateway secret
            serverName: safeName,
          });
        }
      }
    }

    // Generate VPN gateway client entries (one per VPN server)
    // This handles CHR masquerade: all NAS packets arrive from the gateway IP
    if (vpnGateways.size > 0) {
      lines.push('# --- VPN Server Gateway Clients ---');
      lines.push('# When CHR VPN server masquerades traffic, all NAS packets');
      lines.push('# arrive from the gateway IP. All NAS behind the same VPN');
      lines.push('# server MUST use the same RADIUS shared secret.');
      lines.push('');

      for (const [, gw] of vpnGateways) {
        lines.push(`client vpn_gw_${gw.serverName} {`);
        lines.push(`    ipaddr = ${gw.gatewayIp}`);
        lines.push(`    secret = ${gw.secret}`);
        lines.push(`    shortname = vpn_gw_${gw.serverName}`);
        lines.push(`    nas_type = other`);
        lines.push(`    require_message_authenticator = no`);
        lines.push(`    limit_proxy_state = no`);
        lines.push(`}`);
        lines.push('');
      }
    }

    const newContent = lines.join('\n');

    // Compare with current file — only write if different
    let currentContent = '';
    try {
      currentContent = await readFile(NAS_CLIENTS_FILE, 'utf8');
    } catch {
      // File doesn't exist yet — will be created
    }

    if (currentContent.trim() === newContent.trim()) {
      console.log(`[FreeRADIUS] NAS config already in sync (${nasEntries.length} entries)`);
      return false;
    }

    // Ensure directory exists and write updated config
    await execAsync('mkdir -p /etc/freeradius/3.0/clients.d');
    await writeFile(NAS_CLIENTS_FILE, newContent, 'utf8');

    // Ensure clients.d is included in clients.conf
    const { stdout: confContent } = await execAsync('cat /etc/freeradius/3.0/clients.conf').catch(() => ({ stdout: '' }));
    if (!confContent.includes('$INCLUDE clients.d/')) {
      await execAsync(`echo '\n$INCLUDE clients.d/' >> /etc/freeradius/3.0/clients.conf`);
    }

    console.log(`[FreeRADIUS] NAS config updated (${nasEntries.length} entries, ${vpnGateways.size} VPN gateways) — reload required`);
    return true;
  } catch (error: any) {
    console.error('[FreeRADIUS] Failed to sync NAS clients:', error.message);
    return false;
  }
}

/**
 * Restart FreeRADIUS service
 * Requires sudoers permission for PM2 user
 */
export async function reloadFreeRadius(): Promise<void> {
  const now = Date.now();
  
  // Prevent concurrent restarts
  if (now - lastRestartTime < RESTART_COOLDOWN) {
    console.log('FreeRADIUS restart skipped (cooldown active)');
    return;
  }

  try {
    lastRestartTime = now;

    // Sync NAS clients to clients.d before restart — only restart if config changed
    const configChanged = await syncNasClients();

    if (!configChanged) {
      console.log('[FreeRADIUS] Config unchanged, skipping restart');
      return;
    }

    // Restart FreeRADIUS service via sudo
    const { stdout, stderr } = await execAsync('sudo systemctl restart freeradius', {
      timeout: 10000, // 10 second timeout
    });

    if (stderr) {
      console.error('FreeRADIUS restart stderr:', stderr);
    }

    console.log('FreeRADIUS restarted successfully');
  } catch (error: any) {
    console.error('Failed to restart FreeRADIUS:', error.message);
    // Don't throw error - NAS update is more important
    // FreeRADIUS can be restarted manually if needed
  }
}
