#!/usr/bin/env python3
"""
Build a self-contained SALFANET RADIUS installer.

Embeds all component scripts via base64 so the installer works as a single
standalone file — no network access needed at install time.

Usage:
    python3 build-standalone.py [output-file]
    python3 build-standalone.py installer-linux-amd64
"""

import os
import sys
import re
import base64

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = sys.argv[1] if len(sys.argv) > 1 else 'installer-linux-amd64'

# Order matters: common.sh must come first (defines shared functions)
COMPONENT_SCRIPTS = [
    'common.sh',
    'install-system.sh',
    'install-nodejs.sh',
    'install-mysql.sh',
    'install-app.sh',
    'install-freeradius.sh',
    'install-nginx.sh',
    'install-pm2.sh',
    'install-apk.sh',
    'install-vpn-client.sh',
]


def build():
    lines = [
        '#!/bin/bash',
        '# SALFANET RADIUS Installer — Self-Contained Bundle',
        '# Auto-generated by build-standalone.py — do not edit directly.',
        '# To modify: edit vps-install/*.sh then re-run build or push a new tag.',
        '',
        'set -e',
        'set -o pipefail',
        '',
        '# ── Extract embedded component scripts to a temporary directory ──────',
        '_SALFANET_TMP=$(mktemp -d /tmp/salfanet-install.XXXXXX)',
        "trap 'rm -rf \"$_SALFANET_TMP\"' EXIT",
        'SCRIPT_DIR="$_SALFANET_TMP"',
        '',
    ]

    for script in COMPONENT_SCRIPTS:
        src = os.path.join(SCRIPT_DIR, script)
        if not os.path.exists(src):
            print(f'  [WARN] {script} not found, skipping', file=sys.stderr)
            continue

        with open(src, 'rb') as f:
            b64 = base64.b64encode(f.read()).decode()

        marker = '__B64_{}__'.format(
            script.upper().replace('-', '_').replace('.', '_')
        )
        lines.append(f'# Embedded: {script}')
        lines.append(f"base64 -d > \"$_SALFANET_TMP/{script}\" << '{marker}'")
        # Standard 76-char lines
        for i in range(0, len(b64), 76):
            lines.append(b64[i:i + 76])
        lines.append(marker)
        lines.append(f'chmod +x "$_SALFANET_TMP/{script}"')
        lines.append('')
        print(f'  Embedded: {script} ({len(b64) // 1024 + 1} KB base64)')

    # ── Append vps-installer.sh main logic ───────────────────────────────────
    main_path = os.path.join(SCRIPT_DIR, 'vps-installer.sh')
    with open(main_path) as f:
        main = f.read()

    # Remove shebang (already at top)
    main = re.sub(r'^#!/[^\n]*\n', '', main)
    # Remove duplicate set -e / set -o pipefail (already at top)
    main = re.sub(r'^set -e\n', '', main, flags=re.MULTILINE)
    main = re.sub(r'^set -o pipefail\n', '', main, flags=re.MULTILINE)
    # Remove SCRIPT_DIR= line (already set to $_SALFANET_TMP above)
    main = re.sub(r'^SCRIPT_DIR=[^\n]*\n', '', main, flags=re.MULTILINE)

    # The bootstrap block (if [ ! -f "$SCRIPT_DIR/common.sh" ]) will naturally
    # be skipped at runtime since common.sh was just extracted above — no need
    # to strip it; the condition will be false.

    lines.append('# ── Main installer logic ─────────────────────────────────────────────')
    lines.append(main.lstrip('\n'))

    content = '\n'.join(lines)
    with open(OUTPUT, 'w', newline='\n') as f:
        f.write(content)

    os.chmod(OUTPUT, 0o755)
    size = os.path.getsize(OUTPUT)
    lc = content.count('\n')
    print(f'[OK] {OUTPUT}: {lc} lines, {size:,} bytes ({size // 1024} KB)')


if __name__ == '__main__':
    print('Building self-contained installer...')
    build()
